package PAPS::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PAPS::Database::papsdb::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=papsdb',
        user => 'papsuser',
        password => '',
        AutoCommit => q{1},
    }
);

=head1 NAME

PAPS::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PAPS>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PAPS::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Charles Macanka

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
